"""
otel_engine.py — Full Observability for ARIA AI.

Integrates OpenTelemetry, Prometheus, and Grafana for:
  - Distributed tracing of all operations (OpenTelemetry)
  - Real-time business and system metrics (Prometheus)
  - Executive dashboard visualization (Grafana)

Extends the existing trace_engine.py with production-grade observability.

Architecture:
    ARIA Agents → OpenTelemetry SDK → OTLP Exporter → Prometheus → Grafana

Reference:
  - OpenTelemetry: https://opentelemetry.io/docs/instrumentation/python/
  - Prometheus: https://github.com/prometheus/client_python
  - Grafana: https://grafana.com/docs/
"""

from __future__ import annotations

import logging
import time
from collections.abc import AsyncGenerator, Generator
from contextlib import asynccontextmanager, contextmanager
from typing import Any

logger = logging.getLogger("aria.otel_engine")

# ── OpenTelemetry Import with fallback ───────────────────────────────────────
try:
    from opentelemetry import metrics, trace
    from opentelemetry.exporter.otlp.proto.grpc.metric_exporter import (
        OTLPMetricExporter,  # noqa: F401
    )
    from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
    from opentelemetry.sdk.metrics import MeterProvider  # noqa: F401
    from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader  # noqa: F401
    from opentelemetry.sdk.resources import SERVICE_NAME, Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import BatchSpanProcessor

    OTEL_AVAILABLE = True
    logger.info("[OpenTelemetry] SDK loaded successfully.")
except ImportError:
    OTEL_AVAILABLE = False
    logger.warning(
        "[OpenTelemetry] SDK not installed. "
        "Using native tracing. "
        "Install with: pip install opentelemetry-sdk opentelemetry-exporter-otlp"
    )
    trace = None  # type: ignore[assignment]
    metrics = None  # type: ignore[assignment]

# ── Prometheus Import with fallback ──────────────────────────────────────────
try:
    from prometheus_client import (
        CONTENT_TYPE_LATEST,  # noqa: F401
        CollectorRegistry,  # noqa: F401
        Counter,
        Gauge,
        Histogram,
        Summary,  # noqa: F401
        generate_latest,  # noqa: F401
        start_http_server,
    )

    PROMETHEUS_AVAILABLE = True
    logger.info("[Prometheus] Client loaded successfully.")
except ImportError:
    PROMETHEUS_AVAILABLE = False
    logger.warning(
        "[Prometheus] prometheus-client not installed. "
        "Install with: pip install prometheus-client"
    )
    Counter = None  # type: ignore[assignment,misc]
    Gauge = None  # type: ignore[assignment,misc]
    Histogram = None  # type: ignore[assignment,misc]


# ── FastAPI Instrumentation ──────────────────────────────────────────────────
try:
    from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

    FASTAPI_INSTRUMENTATION_AVAILABLE = True
except ImportError:
    FASTAPI_INSTRUMENTATION_AVAILABLE = False
    FastAPIInstrumentor = None  # type: ignore[assignment,misc]


# ── Prometheus Metrics for ARIA ──────────────────────────────────────────────


class AriaPrometheusMetrics:
    """
    Prometheus metrics for ARIA AI.

    Exposes business and system metrics at /metrics for Prometheus.
    Grafana visualizes these metrics in executive dashboards.
    """

    def __init__(self) -> None:
        self._initialized = False
        self._registry: Any = None
        self._metrics: dict[str, Any] = {}

        if PROMETHEUS_AVAILABLE:
            self._setup_metrics()

    def _setup_metrics(self) -> None:
        """Configures all Prometheus metrics for ARIA."""
        try:
            # ── Business Metrics ────────────────────────────────────────────
            self._metrics["revenue_total"] = Counter(
                "aria_revenue_total_usd",
                "Total revenue generated by ARIA in USD",
                ["channel", "product", "agent"],
            )

            self._metrics["sales_total"] = Counter(
                "aria_sales_total",
                "Total number of completed sales",
                ["product", "channel"],
            )

            self._metrics["leads_generated"] = Counter(
                "aria_leads_generated_total",
                "Total number of leads generated",
                ["source", "niche"],
            )

            self._metrics["campaigns_active"] = Gauge(
                "aria_campaigns_active",
                "Number of currently active campaigns",
                ["channel"],
            )

            # ── Agent Metrics ────────────────────────────────────────────────
            self._metrics["agent_executions"] = Counter(
                "aria_agent_executions_total",
                "Total executions per agent",
                ["agent_name", "success"],
            )

            self._metrics["agent_duration"] = Histogram(
                "aria_agent_duration_seconds",
                "Agent execution duration in seconds",
                ["agent_name"],
                buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
            )

            self._metrics["agent_roi"] = Gauge(
                "aria_agent_roi_usd",
                "Current ROI per agent in USD",
                ["agent_name"],
            )

            # ── System Metrics ───────────────────────────────────────────────
            self._metrics["llm_calls"] = Counter(
                "aria_llm_calls_total",
                "Total LLM calls",
                ["model", "agent"],
            )

            self._metrics["llm_tokens"] = Counter(
                "aria_llm_tokens_total",
                "Total tokens consumed",
                ["model", "type"],  # type: input/output
            )

            self._metrics["memory_operations"] = Counter(
                "aria_memory_operations_total",
                "Memory operations (Supabase, Redis, Graphiti, Zep)",
                ["backend", "operation"],
            )

            self._metrics["crawl_requests"] = Counter(
                "aria_crawl_requests_total",
                "Crawling requests (Crawl4AI, Firecrawl)",
                ["source", "success"],
            )

            self._metrics["experiments_active"] = Gauge(
                "aria_experiments_active",
                "Active A/B experiments (GrowthBook)",
            )

            self._metrics["autonomous_cycles"] = Counter(
                "aria_autonomous_cycles_total",
                "Completed autonomous cycles",
                ["status"],
            )

            self._initialized = True
            logger.info("[Prometheus] %d metrics configured", len(self._metrics))

        except Exception as exc:
            logger.error("[Prometheus] Error configuring metrics: %s", exc)

    def record_revenue(
        self,
        amount_usd: float,
        channel: str = "unknown",
        product: str = "unknown",
        agent: str = "unknown",
    ) -> None:
        """Records generated revenue."""
        if not self._initialized:
            return
        try:
            self._metrics["revenue_total"].labels(
                channel=channel, product=product, agent=agent
            ).inc(amount_usd)
            self._metrics["sales_total"].labels(product=product, channel=channel).inc()
        except Exception as exc:
            logger.debug("[Prometheus] Error recording revenue: %s", exc)

    def record_agent_execution(
        self,
        agent_name: str,
        success: bool,
        duration_seconds: float,
        roi: float = 0.0,
    ) -> None:
        """Records an agent execution."""
        if not self._initialized:
            return
        try:
            self._metrics["agent_executions"].labels(
                agent_name=agent_name,
                success=str(success).lower(),
            ).inc()
            self._metrics["agent_duration"].labels(agent_name=agent_name).observe(duration_seconds)
            if roi != 0:
                self._metrics["agent_roi"].labels(agent_name=agent_name).set(roi)
        except Exception as exc:
            logger.debug("[Prometheus] Error recording agent: %s", exc)

    def record_llm_call(
        self,
        model: str,
        agent: str,
        input_tokens: int = 0,
        output_tokens: int = 0,
    ) -> None:
        """Records an LLM call."""
        if not self._initialized:
            return
        try:
            self._metrics["llm_calls"].labels(model=model, agent=agent).inc()
            if input_tokens:
                self._metrics["llm_tokens"].labels(model=model, type="input").inc(input_tokens)
            if output_tokens:
                self._metrics["llm_tokens"].labels(model=model, type="output").inc(output_tokens)
        except Exception as exc:
            logger.debug("[Prometheus] Error recording LLM call: %s", exc)

    def record_crawl(self, source: str, success: bool) -> None:
        """Records a crawling request."""
        if not self._initialized:
            return
        try:
            self._metrics["crawl_requests"].labels(
                source=source, success=str(success).lower()
            ).inc()
        except Exception as exc:
            logger.debug("[Prometheus] Error recording crawl: %s", exc)

    def record_autonomous_cycle(self, status: str = "completed") -> None:
        """Records an autonomous cycle."""
        if not self._initialized:
            return
        try:
            self._metrics["autonomous_cycles"].labels(status=status).inc()
        except Exception as exc:
            logger.debug("[Prometheus] Error recording cycle: %s", exc)

    def get_metrics_text(self) -> str:
        """Generates the metrics text in Prometheus format."""
        if not PROMETHEUS_AVAILABLE:
            return "# Prometheus not available\n"
        try:
            from prometheus_client import REGISTRY, generate_latest

            return generate_latest(REGISTRY).decode("utf-8")
        except Exception as exc:
            return f"# Error generating metrics: {exc}\n"

    def start_metrics_server(self, port: int = 9090) -> None:
        """Starts the Prometheus metrics HTTP server."""
        if not PROMETHEUS_AVAILABLE:
            logger.warning("[Prometheus] Not available, cannot start server")
            return
        try:
            start_http_server(port)
            logger.info("[Prometheus] Metrics server started on port %d", port)
        except Exception as exc:
            logger.error("[Prometheus] Error starting server: %s", exc)


# ── OpenTelemetry Tracer ─────────────────────────────────────────────────────


class AriaOtelTracer:
    """
    OpenTelemetry tracer for ARIA AI.

    Tracks all agent operations with distributed spans,
    enabling analysis of latency, errors, and dependencies.
    """

    def __init__(
        self,
        service_name: str = "aria-ai",
        otlp_endpoint: str = "http://localhost:4317",
    ) -> None:
        self._service_name = service_name
        self._otlp_endpoint = otlp_endpoint
        self._tracer: Any = None
        self._initialized = False

    def initialize(self) -> bool:
        """Initializes the OpenTelemetry TracerProvider."""
        if not OTEL_AVAILABLE:
            logger.warning("[OpenTelemetry] SDK not available")
            return False

        try:
            resource = Resource.create({SERVICE_NAME: self._service_name})

            # Configure OTLP exporter (for Jaeger, Tempo, etc.)
            otlp_exporter = OTLPSpanExporter(endpoint=self._otlp_endpoint)

            provider = TracerProvider(resource=resource)
            provider.add_span_processor(BatchSpanProcessor(otlp_exporter))
            trace.set_tracer_provider(provider)

            self._tracer = trace.get_tracer(self._service_name)
            self._initialized = True
            logger.info(
                "[OpenTelemetry] TracerProvider initialized (endpoint=%s)", self._otlp_endpoint
            )
            return True

        except Exception as exc:
            logger.warning("[OpenTelemetry] Error initializing: %s — using noop tracer", exc)
            if OTEL_AVAILABLE:
                self._tracer = trace.get_tracer(self._service_name)
                self._initialized = True
            return False

    def instrument_fastapi(self, app: Any) -> None:
        """Automatically instruments ARIA's FastAPI app."""
        if not FASTAPI_INSTRUMENTATION_AVAILABLE:
            logger.warning("[OpenTelemetry] FastAPI instrumentation not available")
            return
        try:
            FastAPIInstrumentor.instrument_app(app)
            logger.info("[OpenTelemetry] FastAPI instrumented successfully")
        except Exception as exc:
            logger.warning("[OpenTelemetry] Error instrumenting FastAPI: %s", exc)

    @contextmanager
    def trace_operation(
        self,
        operation_name: str,
        attributes: dict[str, Any] | None = None,
    ) -> Generator:
        """
        Context manager for tracing a synchronous operation.

        Usage:
            with tracer.trace_operation("agent.execute", {"agent": "cfo"}):
                result = agent.execute(task)
        """
        if not self._initialized or not OTEL_AVAILABLE:
            yield None
            return

        with self._tracer.start_as_current_span(operation_name) as span:
            if attributes:
                for key, value in attributes.items():
                    span.set_attribute(key, str(value))
            try:
                yield span
            except Exception as exc:
                span.record_exception(exc)
                span.set_status(trace.StatusCode.ERROR, str(exc))
                raise

    @asynccontextmanager
    async def trace_async_operation(
        self,
        operation_name: str,
        attributes: dict[str, Any] | None = None,
    ) -> AsyncGenerator:
        """
        Context manager for tracing an asynchronous operation.

        Usage:
            async with tracer.trace_async_operation("agent.execute", {"agent": "cfo"}):
                result = await agent.execute(task)
        """
        if not self._initialized or not OTEL_AVAILABLE:
            yield None
            return

        with self._tracer.start_as_current_span(operation_name) as span:
            if attributes:
                for key, value in attributes.items():
                    span.set_attribute(key, str(value))
            try:
                yield span
            except Exception as exc:
                span.record_exception(exc)
                span.set_status(trace.StatusCode.ERROR, str(exc))
                raise

    def get_current_trace_id(self) -> str:
        """Returns the current trace ID for log correlation."""
        if not OTEL_AVAILABLE:
            return ""
        try:
            span = trace.get_current_span()
            ctx = span.get_span_context()
            return format(ctx.trace_id, "032x") if ctx.trace_id else ""
        except Exception:
            return ""


# ── Unified Observability Engine ─────────────────────────────────────────────


class AriaObservabilityEngine:
    """
    Unified observability engine for ARIA AI.

    Combines:
    - OpenTelemetry: distributed tracing of operations
    - Prometheus: business and system metrics
    - Grafana: visualization (via docker-compose)

    Extends the existing trace_engine.py with production-grade capabilities.

    Integrates with:
    - ExecutionPipeline (tracing every execution)
    - BaseAgent (per-agent metrics)
    - FastAPI server (automatic instrumentation)
    - All specialized agents
    """

    def __init__(
        self,
        service_name: str = "aria-ai",
        otlp_endpoint: str = "http://localhost:4317",
        prometheus_port: int = 9090,
    ) -> None:
        self.tracer = AriaOtelTracer(
            service_name=service_name,
            otlp_endpoint=otlp_endpoint,
        )
        self.metrics = AriaPrometheusMetrics()
        self._prometheus_port = prometheus_port

    def initialize(self, fastapi_app: Any = None) -> dict[str, bool]:
        """
        Initializes all observability components.

        Args:
            fastapi_app: FastAPI app for automatic instrumentation

        Returns:
            Dict with the status of each component
        """
        otel_ok = self.tracer.initialize()

        if fastapi_app:
            self.tracer.instrument_fastapi(fastapi_app)

        return {
            "opentelemetry": otel_ok,
            "prometheus": self.metrics._initialized,
            "fastapi_instrumented": fastapi_app is not None and FASTAPI_INSTRUMENTATION_AVAILABLE,
        }

    def start_metrics_server(self) -> None:
        """Starts the Prometheus metrics server."""
        self.metrics.start_metrics_server(self._prometheus_port)

    async def instrument_agent_execution(
        self,
        agent_name: str,
        operation: str,
        context: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Instruments an agent execution with tracing and metrics.

        Usage:
            async with engine.instrument_agent_execution("cfo", "generate_revenue"):
                result = await cfo_agent.execute(context)

        Returns:
            Dict with trace_id and instrumentation metadata
        """
        start_time = time.monotonic()
        span_name = f"aria.agent.{agent_name}.{operation}"

        trace_id = self.tracer.get_current_trace_id()

        return {
            "trace_id": trace_id,
            "agent": agent_name,
            "operation": operation,
            "start_time": start_time,
            "span_name": span_name,
        }

    def record_execution_complete(
        self,
        instrument_result: dict[str, Any],
        success: bool,
        roi: float = 0.0,
    ) -> None:
        """
        Records the completion of an instrumented execution.

        Args:
            instrument_result: Result of instrument_agent_execution
            success: Whether it succeeded
            roi: ROI generated
        """
        start_time = instrument_result.get("start_time", time.monotonic())
        duration = time.monotonic() - start_time
        agent_name = instrument_result.get("agent", "unknown")

        self.metrics.record_agent_execution(
            agent_name=agent_name,
            success=success,
            duration_seconds=duration,
            roi=roi,
        )

    def get_health_status(self) -> dict[str, Any]:
        """Health status of the observability system."""
        return {
            "opentelemetry": {
                "available": OTEL_AVAILABLE,
                "initialized": self.tracer._initialized,
                "endpoint": self.tracer._otlp_endpoint,
            },
            "prometheus": {
                "available": PROMETHEUS_AVAILABLE,
                "initialized": self.metrics._initialized,
                "metrics_count": len(self.metrics._metrics),
                "port": self._prometheus_port,
            },
            "grafana": {
                "info": "Configured via docker-compose.yml",
                "default_port": 3000,
            },
        }


# ── Singleton ────────────────────────────────────────────────────────────────
_observability_instance: AriaObservabilityEngine | None = None


def get_observability_engine() -> AriaObservabilityEngine:
    """Returns the singleton ARIA observability engine."""
    global _observability_instance
    if _observability_instance is None:
        import os

        _observability_instance = AriaObservabilityEngine(
            service_name=os.getenv("OTEL_SERVICE_NAME", "aria-ai"),
            otlp_endpoint=os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4317"),
            prometheus_port=int(os.getenv("PROMETHEUS_PORT", "9090")),
        )
    return _observability_instance
