"""
pdf_generator.py — Generates structured PDFs using fpdf2 (pure Python, no system deps).
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("aria.pdf_generator")


class PDFGenerator:
    """Generates PDFs with a title, sections, and text content."""

    def generate(
        self,
        title: str,
        content: str = "",
        sections: list[dict] | None = None,
        author: str = "ARIA AI",
    ) -> bytes:
        """
        Generates a PDF and returns the bytes.

        sections: list of dicts with {"title": str, "body": str}
        content: plain text if there are no structured sections
        """
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_creator(author)

        # Cover / Title
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 12, title, align="C")
        pdf.ln(4)

        # Separator line
        pdf.set_draw_color(180, 180, 180)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(6)

        if sections:
            for sec in sections:
                sec_title = sec.get("title", "")
                sec_body = sec.get("body", "")

                if sec_title:
                    pdf.set_font("Helvetica", "B", 14)
                    pdf.set_text_color(50, 80, 150)
                    pdf.multi_cell(0, 8, sec_title)
                    pdf.ln(2)

                if sec_body:
                    pdf.set_font("Helvetica", "", 11)
                    pdf.set_text_color(40, 40, 40)
                    # Split lines manually to handle \n in body text
                    for line in sec_body.split("\n"):
                        pdf.multi_cell(0, 6, line if line else " ")
                    pdf.ln(4)
        elif content:
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(40, 40, 40)
            for line in content.split("\n"):
                pdf.multi_cell(0, 6, line if line else " ")

        # Footer
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, f"Generated by {author}", align="C")

        return bytes(pdf.output())


async def generate_pdf(
    title: str,
    content: str = "",
    sections: list[dict] | None = None,
) -> dict[str, Any]:
    """Async wrapper — fpdf2 is synchronous but fast."""
    try:
        gen = PDFGenerator()
        pdf_bytes = gen.generate(title=title, content=content, sections=sections)
        return {
            "success": True,
            "pdf_bytes": pdf_bytes,
            "filename": f"{title[:40].replace(' ', '_')}.pdf",
            "size_kb": len(pdf_bytes) // 1024,
        }
    except Exception as exc:
        logger.error("[PDFGenerator] %s", exc, exc_info=True)
        return {"success": False, "error": str(exc)}
