"""
graphiti_client.py — Temporal Knowledge Graph Memory for ARIA AI with Graphiti.

Graphiti builds temporal knowledge graphs that allow ARIA to:
  - Track relationships between entities over time
  - Attribute revenue across complete causal chains:
      video → lead → email → sale → renewal
  - Query what was true at any point in time
  - Detect changes in relationships and strategies

Integration with Aria:
  - Extends EvolutionaryMemory with temporal graph capabilities
  - Connects to FalkorDB (via Docker) or Neo4j
  - Complements the existing Supabase/Redis memory

Reference: https://github.com/getzep/graphiti
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

logger = logging.getLogger("aria.graphiti_client")

# ── Graphiti import with fallback ────────────────────────────────────────────
try:
    from graphiti_core import Graphiti
    from graphiti_core.nodes import EpisodeType  # noqa: F401
    from graphiti_core.search.search_config_recipes import (
        EDGE_HYBRID_SEARCH_RRF,  # noqa: F401
        NODE_HYBRID_SEARCH_RRF,  # noqa: F401
    )

    GRAPHITI_AVAILABLE = True
    logger.info("[Graphiti] Library loaded successfully.")
except ImportError:
    GRAPHITI_AVAILABLE = False
    logger.warning(
        "[Graphiti] graphiti-core not installed. "
        "Using in-memory graph implementation. "
        "Install with: pip install graphiti-core[falkordb]"
    )
    Graphiti = None  # type: ignore[assignment,misc]


# ── In-Memory Graph Fallback Implementation ──────────────────────────────────


class InMemoryGraph:
    """
    In-memory knowledge graph used as a fallback for Graphiti.
    Keeps the same interface for compatibility.
    """

    def __init__(self) -> None:
        self._nodes: dict[str, dict] = {}
        self._edges: list[dict] = []
        self._episodes: list[dict] = []

    async def add_episode(
        self,
        name: str,
        episode_body: str,
        source_description: str = "",
        reference_time: datetime | None = None,
        source: str = "text",
    ) -> None:
        episode = {
            "name": name,
            "body": episode_body,
            "source": source,
            "source_description": source_description,
            "timestamp": (reference_time or datetime.now(UTC)).isoformat(),
        }
        self._episodes.append(episode)
        logger.debug("[InMemoryGraph] Episode added: %s", name)

    async def search(self, query: str, num_results: int = 5) -> list[dict]:
        query_lower = query.lower()
        results = []
        for ep in self._episodes:
            if query_lower in ep["body"].lower() or query_lower in ep["name"].lower():
                results.append(ep)
            if len(results) >= num_results:
                break
        return results

    async def close(self) -> None:
        pass


# ── Business Entities for ARIA AI ────────────────────────────────────────────

# Entity types in ARIA's knowledge graph
ARIA_ENTITY_TYPES = {
    "Lead": "Prospect or potential customer identified",
    "Sale": "Completed sale with amount and date",
    "Product": "Digital product or service offered",
    "Campaign": "Marketing campaign executed",
    "Content": "Content created (video, post, ebook, etc.)",
    "Revenue": "Revenue generated with attribution",
    "Competitor": "Competitor analyzed in the market",
    "Niche": "Market niche identified",
    "Strategy": "Strategy executed with results",
    "Agent": "ARIA agent that performed an action",
}

# Temporal relationship types
ARIA_RELATION_TYPES = {
    "GENERATED": "One entity generated another (content → lead)",
    "CONVERTED": "One entity converted into another (lead → sale)",
    "ATTRIBUTED_TO": "Revenue is attributed to a source",
    "EXECUTED_BY": "An action was performed by an agent",
    "PART_OF": "Belongs to a campaign or strategy",
    "FOLLOWED_BY": "Temporal sequence of events",
    "RENEWED": "Renewal of a previous sale",
}


# ── Main Graphiti Client for ARIA ────────────────────────────────────────────


class AriaGraphitiClient:
    """
    Graphiti client for ARIA AI.

    Builds and queries ARIA's temporal knowledge graph, enabling
    complete revenue attribution and analysis of causal relationships
    between actions and outcomes.

    Usage:
        client = AriaGraphitiClient()
        await client.initialize()

        # Record a business event
        await client.record_business_event(
            event_type="sale",
            entity_name="Fitness Pro Ebook",
            description="$27 USD sale generated by TikTok campaign",
            metadata={"amount": 27.0, "source": "tiktok_campaign_001"}
        )

        # Query revenue attribution
        results = await client.query_revenue_attribution("TikTok")
    """

    def __init__(
        self,
        neo4j_uri: str = "bolt://localhost:7687",
        neo4j_user: str = "neo4j",
        neo4j_password: str = "password",
        use_falkordb: bool = True,
        falkordb_host: str = "localhost",
        falkordb_port: int = 6379,
    ) -> None:
        self._graphiti: Any = None
        self._fallback: InMemoryGraph | None = None
        self._neo4j_uri = neo4j_uri
        self._neo4j_user = neo4j_user
        self._neo4j_password = neo4j_password
        self._use_falkordb = use_falkordb
        self._falkordb_host = falkordb_host
        self._falkordb_port = falkordb_port
        self._initialized = False

    async def initialize(self) -> bool:
        """
        Initializes the connection to Graphiti (FalkorDB or Neo4j).
        Returns True if it connected successfully, False if using the fallback.
        """
        if not GRAPHITI_AVAILABLE:
            logger.warning("[Graphiti] Using in-memory graph as fallback")
            self._fallback = InMemoryGraph()
            self._initialized = True
            return False

        try:
            if self._use_falkordb:
                # FalkorDB is lighter and easier to deploy with Docker
                from graphiti_core.driver.falkordb_driver import FalkorDBDriver

                driver = FalkorDBDriver(
                    host=self._falkordb_host,
                    port=self._falkordb_port,
                )
                self._graphiti = Graphiti.from_driver(driver)
            else:
                # Neo4j for enterprise production
                self._graphiti = Graphiti(
                    uri=self._neo4j_uri,
                    user=self._neo4j_user,
                    password=self._neo4j_password,
                )

            await self._graphiti.build_indices_and_constraints()
            self._initialized = True
            logger.info("[Graphiti] Connection established successfully")
            return True

        except Exception as exc:
            logger.warning("[Graphiti] Error connecting: %s — using fallback", exc)
            self._fallback = InMemoryGraph()
            self._initialized = True
            return False

    async def record_business_event(
        self,
        event_type: str,
        entity_name: str,
        description: str,
        metadata: dict[str, Any] | None = None,
        reference_time: datetime | None = None,
    ) -> bool:
        """
        Records a business event in the temporal graph.

        Examples:
            event_type="content_created", entity_name="TikTok Fitness Video"
            event_type="lead_generated", entity_name="Lead #1234"
            event_type="sale_completed", entity_name="Fitness Pro Ebook"
            event_type="revenue_attributed", entity_name="$27 USD"

        Args:
            event_type: Event type (content_created, lead_generated, sale_completed, etc.)
            entity_name: Name of the entity involved
            description: Detailed description of the event
            metadata: Additional data (amount, source, agent, etc.)
            reference_time: Event timestamp (default: now)

        Returns:
            True if recorded successfully
        """
        if not self._initialized:
            await self.initialize()

        meta_str = ""
        if metadata:
            meta_str = " | ".join(f"{k}={v}" for k, v in metadata.items())

        episode_body = f"[{event_type.upper()}] {entity_name}: {description}"
        if meta_str:
            episode_body += f" | Metadata: {meta_str}"

        try:
            if self._graphiti:
                await self._graphiti.add_episode(
                    name=f"{event_type}_{entity_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
                    episode_body=episode_body,
                    source_description=f"ARIA AI - {event_type}",
                    reference_time=reference_time or datetime.now(UTC),
                    source="text",
                )
            elif self._fallback:
                await self._fallback.add_episode(
                    name=f"{event_type}_{entity_name}",
                    episode_body=episode_body,
                    source_description=f"ARIA AI - {event_type}",
                    reference_time=reference_time,
                )
            logger.info("[Graphiti] Event recorded: %s | %s", event_type, entity_name)
            return True

        except Exception as exc:
            logger.error("[Graphiti] Error recording event: %s", exc)
            return False

    async def record_revenue_chain(
        self,
        chain: list[dict[str, Any]],
        total_revenue_usd: float,
    ) -> bool:
        """
        Records a complete revenue attribution chain.

        Example chain:
            [
                {"type": "content", "name": "TikTok Video #42", "timestamp": "..."},
                {"type": "lead", "name": "Lead Juan Garcia", "timestamp": "..."},
                {"type": "email", "name": "Email Sequence #3", "timestamp": "..."},
                {"type": "sale", "name": "Ebook $27", "timestamp": "..."},
                {"type": "renewal", "name": "Monthly Renewal", "timestamp": "..."},
            ]

        Args:
            chain: List of events in chronological order
            total_revenue_usd: Total revenue attributed to this chain
        """
        if not chain:
            return False

        chain_description = " → ".join(
            f"{step.get('type', '?')}:{step.get('name', '?')}" for step in chain
        )

        return await self.record_business_event(
            event_type="revenue_chain",
            entity_name=f"Chain ${total_revenue_usd:.2f}",
            description=f"Attribution chain: {chain_description}",
            metadata={
                "total_revenue_usd": total_revenue_usd,
                "chain_length": len(chain),
                "first_touch": chain[0].get("name", ""),
                "last_touch": chain[-1].get("name", ""),
            },
        )

    async def query_revenue_attribution(
        self,
        source: str,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Queries revenue attribution for a specific source.

        Args:
            source: Source to query (e.g.: "TikTok", "email", "ebook")
            limit: Maximum number of results

        Returns:
            List of events related to the source
        """
        if not self._initialized:
            await self.initialize()

        query = f"revenue attribution {source} sales conversion"

        try:
            if self._graphiti:
                results = await self._graphiti.search(query, num_results=limit)
                return [
                    {
                        "fact": r.fact if hasattr(r, "fact") else str(r),
                        "valid_at": (
                            r.valid_at.isoformat()
                            if hasattr(r, "valid_at") and r.valid_at
                            else None
                        ),
                        "source": source,
                    }
                    for r in results
                ]
            if self._fallback:
                return await self._fallback.search(query, num_results=limit)

        except Exception as exc:
            logger.error("[Graphiti] Error in query: %s", exc)

        return []

    async def query_competitor_landscape(
        self,
        niche: str,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Queries the competitor landscape for a niche.

        Args:
            niche: Niche to analyze
            limit: Maximum number of results
        """
        return await self.query_revenue_attribution(
            source=f"competitor {niche}",
            limit=limit,
        )

    async def get_knowledge_summary(self) -> dict[str, Any]:
        """Returns a summary of the knowledge graph's status."""
        if not self._initialized:
            await self.initialize()

        if self._fallback:
            return {
                "backend": "in_memory_fallback",
                "total_episodes": len(self._fallback._episodes),
                "graphiti_available": GRAPHITI_AVAILABLE,
            }

        return {
            "backend": "falkordb" if self._use_falkordb else "neo4j",
            "graphiti_available": GRAPHITI_AVAILABLE,
            "initialized": self._initialized,
        }

    async def close(self) -> None:
        """Closes the connection to the graph."""
        if self._graphiti:
            await self._graphiti.close()
        elif self._fallback:
            await self._fallback.close()


# ── Singleton ────────────────────────────────────────────────────────────────
_graphiti_instance: AriaGraphitiClient | None = None


def get_graphiti_client() -> AriaGraphitiClient:
    """Returns ARIA's Graphiti client singleton."""
    global _graphiti_instance
    if _graphiti_instance is None:
        import os

        _graphiti_instance = AriaGraphitiClient(
            neo4j_uri=os.getenv("NEO4J_URI", "bolt://localhost:7687"),
            neo4j_user=os.getenv("NEO4J_USER", "neo4j"),
            neo4j_password=os.getenv("NEO4J_PASSWORD", "password"),
            use_falkordb=os.getenv("USE_FALKORDB", "true").lower() == "true",
            falkordb_host=os.getenv("FALKORDB_HOST", "localhost"),
            falkordb_port=int(os.getenv("FALKORDB_PORT", "6379")),
        )
    return _graphiti_instance
